### ISSUE TITLE
'Recharge' effect causes an error

### ISSUE THREAD

**Issue by TeddySouth** [MCDMFG/KingdomsAndWarfare#17]
When playing with kingdoms and warfare I have found that whenever a creature uses an ability that applies the Recharge effect such as the giant spider's Web ability, or a red dragon's Fire Breath attack, it causes an exception when the effect would normally cause the dice to be rolled to check if the ability recharges.

I've also noticed after this exception occurs, that new effects cannot be applied to any token or entry in the combat tracker, and effects that were already applied to creatures in the initiative order seem not to function as intended, or sometimes at all. Exiting back to the launcher and relaunching the game fixes this until another Recharge is provoked.

I tracked this bug down to a conflict between this extension and Untrue Effects by Berwind https://forge.fantasygrounds.com/shop/items/591/view

**Comment by MeAndUnique** [comment]
Replied in the Untrue Effects forum post.
