### ISSUE TITLE
Cannot Add NPCs to Combat Tracker or Encounters

### ISSUE THREAD

**Issue by GavinRuneblade** [MCDMFG/KingdomsAndWarfare#20]
This was a larger issue affecting all of FantasyGrounds as discussed here:
https://www.fantasygrounds.com/forums/showthread.php?74402-5e-NPCs-unusable-(&highlight=encounter 

While it is fixed for the main system, it still appears when the current v2.04 extension is loaded and no other extensions are.

When adding an NPC to an encounter an error message appears saying "Only records from campaign record lists can be added to encounters"

When adding an NPC to the combat tracker, a very long string of messages appear, "script execution error: [string "scripts/manager_combat_kw.lua"]179:attempt to call upvalue `[AddNPC' (a nil value)"

Screenshots attached:
![Chat Error](https://user-images.githubusercontent.com/109435451/179368975-4cd2b87f-5e88-48e4-9d4d-1d955978800f.png)

I have confirmed it is not a conflict with another extension as the issue appears even with only the current K&W v2.04 extension loaded.

Edit: need new screenshot, I have one from older version of the extension (I tried reverting).

**Comment by Gtaray** [comment]
> This was a larger issue affecting all of FantasyGrounds as discussed here: https://www.fantasygrounds.com/forums/showthread.php?74402-5e-NPCs-unusable-(&highlight=encounter
> 
> While it is fixed for the main system, it still appears when the current v2.04 extension is loaded and no other extensions are.
> 
> When adding an NPC to an encounter an error message appears saying "Only records from campaign record lists can be added to encounters"
> 
> When adding an NPC to the combat tracker, a very long string of messages appear, "script execution error: [string "scripts/manager_combat_kw.lua"]179:attempt to call upvalue `[AddNPC' (a nil value)"
> 
> Screenshots attached: ![Chat Error](https://user-images.githubusercontent.com/109435451/179368975-4cd2b87f-5e88-48e4-9d4d-1d955978800f.png)
> 
> I have confirmed it is not a conflict with another extension as the issue appears even with only the current K&W v2.04 extension loaded.
> 
> Edit: need new screenshot, I have one from older version of the extension (I tried reverting).

This issue has been fixed and submitted to smiteworks as a hotfix. It's in their hands for when this deploy goes out, unfortunately. I'll leave this open until I can confirm it's fixed in the released version.

**Comment by GavinRuneblade** [comment]
Looks like it is working now.
Cheers!
