### ISSUE TITLE
Drag and Drop of Unit Trait to Unit raises Script Execution Error at manager_combat_kw.lua

### ISSUE THREAD

**Issue by kanbie** [MCDMFG/KingdomsAndWarfare#25]
When dragging a Trait on to a Unit FGU raises a Script Execution Error and points to line 559 on manager_combat_kw.lua

Doesn't appear to affect creating the unit card, not sure why its throwing an error.
![FGU Error](https://user-images.githubusercontent.com/50888594/205468220-3bc74195-6559-4109-b692-cf00f902227b.png)

**Comment by kanbie** [comment]
Worth noting, this is with the official Kingdoms and Warfare module and included extension.

**Comment by Gtaray** [comment]
Just pushed a fix for this. It will be in the Tuesday update via FG.
